### ISSUE TITLE
Earthly action is suddenly taking a lot of time to setup and teardown

### ISSUE THREAD

**Issue by shaft3796** [earthly/actions-setup#112]
Everything is in this screenshot, it takes more than 4mn for setup and for post run, some days ago it was working perfectly in 10s.

![Image](https://github.com/user-attachments/assets/86e85a2f-fb9e-44fd-8680-8b3f4126b914)

```yaml
    steps:  
    - uses: earthly/actions-setup@v1
      with:
        version: v0.8.15
```
