### ISSUE TITLE
Missing glibc

### ISSUE THREAD

**Issue by notmeta** [earthly/actions-setup#35]
Getting this when running this using the v1 tag and 'latest' earthly version
```
Run earthly/actions-setup@v1
  with:
    github-token: ***
    version: latest
    prerelease: false
    use-cache: true
  env:
    AWS_DEFAULT_REGION: eu-west-1
    AWS_REGION: eu-west-1
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***
/opt/actions-runner/externals/node20/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /opt/actions-runner/externals/node20/bin/node)
/opt/actions-runner/externals/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /opt/actions-runner/externals/node20/bin/node)
```

Workflow step:
```yml
      - name: Download latest earthly
        uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: "latest"
```
```[tasklist]
### Tasks
```
