### ISSUE TITLE
Version is not handle correctly

### ISSUE THREAD

**Issue by spontoreau** [earthly/actions-setup#4]
Hello guys, how are you ?

Thanks for the good job, I'm evaluating Earthly and it's a really interesting tool !

On my side I just have a little issue regarding the version parameter of the action and how it is handled by the Github Action. As describe in the documentation I need to specify the version without a "v" at the beginning:

```yaml
- name: Install earthly
  uses: earthly/setup-earthly@v1
  with:
    version: 0.6.1
```

or (for semver range)

```yaml
- name: Install earthly
  uses: earthly/setup-earthly@v1
  with:
    version: ^0.6.0
```

I tried the second one with the semver and get a 404 not found. That's the Yaml I used:
```yaml
name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup earthly
        uses: earthly/actions-setup@v1.0.1
        with:
          version: ^0.6.0

      - name: Compile
        run: earthly +compile
```

And the corresponding error i got:
![image](https://user-images.githubusercontent.com/3357643/169568747-fd00ebbd-686e-403d-b1f3-63c5eeeff52c.png)

Then I tried without semver range to ensure the bug wasn't linked to that.

Here is the second version of the yaml:
```yaml
name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup earthly
        uses: earthly/actions-setup@v1.0.1
        with:
          version: 0.6.0
          
      - name: Compile
        run: earthly +compile
```

I got the same error:
![image](https://user-images.githubusercontent.com/3357643/169569707-7413d034-0ae7-49a0-9a2b-b0547108f5af.png)

Finally I did a last try by adding a "v" in the version:
```yaml
name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup earthly
        uses: earthly/actions-setup@v1.0.1
        with:
          version: v0.6.0
          
      - name: Compile
        run: earthly +compile
```

This one is working:
![image](https://user-images.githubusercontent.com/3357643/169570139-1b18f9db-1a50-4b74-a0a1-18d4f4c8cfe3.png)

I don't know if it's the documentation or the code that is wrong but I would be happy to help fixing that if you tell me what is the expected behavior.

Best,
Sylvain
