### ISSUE TITLE
Semver range version is not working

### ISSUE THREAD

**Issue by vtopc** [earthly/actions-setup#6]
Hey. Looks like installing a version that adheres to a semver range from the https://github.com/earthly/actions-setup#usage is not working.

My GHA workflows:
```
jobs:
  earthly:
    name: Run
    runs-on: ubuntu-latest
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: ^0.6.0 # Install a version that adheres to a semver range

      - name: Earthly version
        run: earthly --version

      - name: Checkout the repo
        uses: actions/checkout@v3
```

error:
```
Run earthly/actions-setup@v1
  with:
    version: ^0.6.0
  env:
    SSH_AUTH_SOCK: /tmp/ssh_agent.sock
Setting up earthly version=^0.6.0
/home/runner/work/_actions/earthly/actions-setup/v1/dist/index.js:498
      throw error;
      ^
Error: Command failed: sudo /bin/sh -c 'wget -q https://github.com/earthly/earthly/releases/download/^0.6.0/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly && /usr/local/bin/earthly bootstrap'
    at ChildProcess.exithandler (child_process.js:308:1[2](https://github.com/vtopc/test/runs/7389537805?check_suite_focus=true#step:2:2))
    at ChildProcess.emit (events.js:[3](https://github.com/vtopc/test/runs/7389537805?check_suite_focus=true#step:2:3)1[4](https://github.com/vtopc/test/runs/7389537805?check_suite_focus=true#step:2:4):20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:[5](https://github.com/vtopc/test/runs/7389537805?check_suite_focus=true#step:2:5)) {
  killed: false,
  code: 8,
  signal: null,
  cmd: "sudo /bin/sh -c 'wget -q https://github.com/earthly/earthly/releases/download/^0.[6](https://github.com/vtopc/test/runs/7389537805?check_suite_focus=true#step:2:7).0/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly && /usr/local/bin/earthly bootstrap'"
}
```

the same for `version: "^0.6.0"`
